insert into company values('BOM500410','ACC Limited	',1);
insert into company values('BOM500103','Bharat Heavy Electricals Limited	',1);
insert into company values('BOM532454','Bharti Airtel Ltd	',1);
insert into company values('BOM532868','DLF Ltd.	',1);
insert into company values('BOM500300','Grasim Industries Ltd.	',1);
insert into company values('BOM500180','HDFC Bank (HDB)	',1);
insert into company values('BOM500010','HDFC	',1);
insert into company values('BOM500440','Hindalco Industries Ltd	',1);
insert into company values('BOM500696','Hindustan Unilever Ltd	',1);
insert into company values('BOM532174','ICICI Bank (IBN)	',1);
insert into company values('BOM500209','Infosys Technologies (INFY)	',1);
insert into company values('BOM500875','ITC Ltd	',1);
insert into company values('BOM532532','Jaiprakash Associates Ltd.	',1);
insert into company values('BOM500510','Larsen & Toubro Limited	',1);
insert into company values('BOM500520','Mahindra & Mahindra Ltd	',1);
insert into company values('BOM532500','Maruti Suzuki India Ltd	',1);
insert into company values('BOM532555','National Thermal Power Corporation Ltd	',1);
insert into company values('BOM500312','Oil and Natural Gas Corporation 	',1);
insert into company values('BOM500359','Ranbaxy Laboratories Ltd.	',1);
insert into company values('BOM532712','Reliance Communications (532712-BY)	',1);
insert into company values('BOM500325','Reliance Industries Limited (RELIANCE-IN)	',1);
insert into company values('BOM500390','Reliance Infrastructure Ltd.	',1);
insert into company values('BOM532540','Tata Consultancy Services Limited	',1);
insert into company values('BOM500570','Tata Motors (TTM)	',1);
insert into company values('BOM500400','Tata Power Company Ltd.	',1);
insert into company values('BOM500470','Tata Steel Limited (500470-BY)	',1);
insert into company values('BOM507685','Wipro (WIT)	',1);

alter table company alter column ticker_symbol type varchar(30);
alter table stock_history alter column ticker_symbol type varchar(30);
alter table ownership alter column ticker_symbol type varchar(30);
alter table curr_transact alter column ticker_symbol type varchar(30);
alter table transact_history alter column ticker_symbol type varchar(30);
alter table company alter column name type varchar(100);
insert into company values('CPSEETF','GOLDMANAMC-CPSEETF',1);
insert into company values('ICCNX100','ICICI Prudential CNX 100 ETF - Growth',1);
insert into company values('RELCNX100','R Shares CNX 100 Fund',1);
insert into company values('NIFETF','ICICI Prudential Nifty ETF - Growth',1);
insert into company values('BSLNIFTY','Birla Sun Life Nifty ETF',1);
insert into company values('M100','MoSt Shares M100',1);
insert into company values('INFRABEES','Goldman Sachs Infrastructure Exchange Traded Scheme',1);
insert into company values('M50','MoSt Shares M50',1);
insert into company values('QNIFTY','Quantum Index Fund',1);
insert into company values('RELBANK','Reliance Banking Exchange Traded Fund',1);
insert into company values('KOTAKPSUBK','Kotak PSU Bank ETF',1);
insert into company values('UTISUNDER','S&P CNX Nifty UTI Notional Depository Reciepts Scheme (SUNDER)',1);
insert into company values('SHARIABEES','Goldman Sachs S&P CNX Nifty Shariah Index Exchange Traded Scheme',1);
insert into company values('PSUBNKBEES','Goldman Sachs PSU Bank Exchange Traded Scheme',1);
insert into company values('BANKBEES','Goldman Sachs Banking Index Exchange Traded Scheme',1);
insert into company values('JUNIORBEES','Goldman Sachs Nifty Junior Exchange Traded Scheme',1);
insert into company values('NIFTYBEES','Goldman Sachs Nifty Exchange Traded Scheme',1);